require('pack')

require('mapping')
require('plugin.compe')
require('plugin.ntree')
require('plugin.lualine')
require('plugin.lspconfig')
require('plugin.autopairs')
require('plugin.themes')
require('settings')
require('plugin.treesitter')
require('plugin.telescope')
require('plugin.lspsaga')
require('plugin.git')
